
package implementationwsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DPSSInterface", targetNamespace = "http://interfaces/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DPSSInterface {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createPlayerAccount", targetNamespace = "http://interfaces/", className = "implementationwsdl.CreatePlayerAccount")
    @ResponseWrapper(localName = "createPlayerAccountResponse", targetNamespace = "http://interfaces/", className = "implementationwsdl.CreatePlayerAccountResponse")
    @Action(input = "http://interfaces/DPSSInterface/createPlayerAccountRequest", output = "http://interfaces/DPSSInterface/createPlayerAccountResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://interfaces/DPSSInterface/createPlayerAccount/Fault/IOException")
    })
    public String createPlayerAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPlayerStatus", targetNamespace = "http://interfaces/", className = "implementationwsdl.GetPlayerStatus")
    @ResponseWrapper(localName = "getPlayerStatusResponse", targetNamespace = "http://interfaces/", className = "implementationwsdl.GetPlayerStatusResponse")
    @Action(input = "http://interfaces/DPSSInterface/getPlayerStatusRequest", output = "http://interfaces/DPSSInterface/getPlayerStatusResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://interfaces/DPSSInterface/getPlayerStatus/Fault/IOException")
    })
    public String getPlayerStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "suspendAccount", targetNamespace = "http://interfaces/", className = "implementationwsdl.SuspendAccount")
    @ResponseWrapper(localName = "suspendAccountResponse", targetNamespace = "http://interfaces/", className = "implementationwsdl.SuspendAccountResponse")
    @Action(input = "http://interfaces/DPSSInterface/suspendAccountRequest", output = "http://interfaces/DPSSInterface/suspendAccountResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://interfaces/DPSSInterface/suspendAccount/Fault/IOException")
    })
    public String suspendAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "playerSignIn", targetNamespace = "http://interfaces/", className = "implementationwsdl.PlayerSignIn")
    @ResponseWrapper(localName = "playerSignInResponse", targetNamespace = "http://interfaces/", className = "implementationwsdl.PlayerSignInResponse")
    @Action(input = "http://interfaces/DPSSInterface/playerSignInRequest", output = "http://interfaces/DPSSInterface/playerSignInResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://interfaces/DPSSInterface/playerSignIn/Fault/IOException")
    })
    public String playerSignIn(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     * @throws InterruptedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "playerSignOut", targetNamespace = "http://interfaces/", className = "implementationwsdl.PlayerSignOut")
    @ResponseWrapper(localName = "playerSignOutResponse", targetNamespace = "http://interfaces/", className = "implementationwsdl.PlayerSignOutResponse")
    @Action(input = "http://interfaces/DPSSInterface/playerSignOutRequest", output = "http://interfaces/DPSSInterface/playerSignOutResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://interfaces/DPSSInterface/playerSignOut/Fault/IOException"),
        @FaultAction(className = InterruptedException_Exception.class, value = "http://interfaces/DPSSInterface/playerSignOut/Fault/InterruptedException")
    })
    public String playerSignOut(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws IOException_Exception, InterruptedException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     * @throws InterruptedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transferAccount", targetNamespace = "http://interfaces/", className = "implementationwsdl.TransferAccount")
    @ResponseWrapper(localName = "transferAccountResponse", targetNamespace = "http://interfaces/", className = "implementationwsdl.TransferAccountResponse")
    @Action(input = "http://interfaces/DPSSInterface/transferAccountRequest", output = "http://interfaces/DPSSInterface/transferAccountResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://interfaces/DPSSInterface/transferAccount/Fault/IOException"),
        @FaultAction(className = InterruptedException_Exception.class, value = "http://interfaces/DPSSInterface/transferAccount/Fault/InterruptedException")
    })
    public String transferAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3)
        throws IOException_Exception, InterruptedException_Exception
    ;

}
