
package implementationwsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NAServerService", targetNamespace = "http://server/", wsdlLocation = "http://localhost:8080/DPSS/NA?wsdl")
public class NAServerService
    extends Service
{

    private final static URL NASERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException NASERVERSERVICE_EXCEPTION;
    private final static QName NASERVERSERVICE_QNAME = new QName("http://server/", "NAServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/DPSS/NA?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NASERVERSERVICE_WSDL_LOCATION = url;
        NASERVERSERVICE_EXCEPTION = e;
    }

    public NAServerService() {
        super(__getWsdlLocation(), NASERVERSERVICE_QNAME);
    }

    public NAServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NASERVERSERVICE_QNAME, features);
    }

    public NAServerService(URL wsdlLocation) {
        super(wsdlLocation, NASERVERSERVICE_QNAME);
    }

    public NAServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NASERVERSERVICE_QNAME, features);
    }

    public NAServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NAServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DPSSInterface
     */
    @WebEndpoint(name = "NAServerPort")
    public DPSSInterface getNAServerPort() {
        return super.getPort(new QName("http://server/", "NAServerPort"), DPSSInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DPSSInterface
     */
    @WebEndpoint(name = "NAServerPort")
    public DPSSInterface getNAServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "NAServerPort"), DPSSInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NASERVERSERVICE_EXCEPTION!= null) {
            throw NASERVERSERVICE_EXCEPTION;
        }
        return NASERVERSERVICE_WSDL_LOCATION;
    }

}
